#!/usr/bin/env node
/**
 * rp-megapool-auditor compare
 *
 * Takes a saved capture bundle (from capture.mjs) and a text dump of
 * `rocketpool megapool status` / `rocketpool megapool validators` output,
 * then produces a structured side-by-side comparison document showing
 * exactly what each tool exposes and what the auditor adds.
 *
 * Usage:
 *   node src/compare.mjs \
 *     --capture capture/ \
 *     --smartnode capture/smartnode-status.txt \
 *     --out capture/comparison.md
 */

import fs from 'node:fs';
import path from 'node:path';

function printHelp() {
  console.log(`
rp-megapool-auditor compare: Side-by-side tooling comparison generator.

USAGE:
  node src/compare.mjs \\
    --capture  capture/ \\
    --smartnode capture/smartnode-status.txt \\
    --out       capture/comparison.md

OPTIONS:
  --capture <dir>      Capture bundle directory produced by capture.mjs
  --smartnode <file>   Text file containing rocketpool megapool status output
  --out <file>         Output path for the Markdown comparison document
  --help               Show this help
`);
}

function args(name, fallback = null) {
  const argv = process.argv.slice(2);
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : fallback;
}

function safeRead(filepath) {
  try { return fs.readFileSync(filepath, 'utf8'); }
  catch { return null; }
}

function safeJson(filepath) {
  const raw = safeRead(filepath);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

function extractSmartnode(text) {
  if (!text) return null;
  // Pull out the fields Smartnode exposes in megapool status / validators
  const state = text.match(/State:\s*(.+)/i)?.[1]?.trim();
  const exitNotified = text.match(/Exit Notified:\s*(.+)/i)?.[1]?.trim();
  const balanceFinalized = text.match(/Balance Finalized:\s*(.+)/i)?.[1]?.trim();
  const beaconIndex = text.match(/Beacon Index:\s*(.+)/i)?.[1]?.trim();
  const nodeAddress = text.match(/Node Address:\s*(.+)/i)?.[1]?.trim();
  return { state, exitNotified, balanceFinalized, beaconIndex, nodeAddress, raw: text };
}

function statusBadge(status) {
  const map = {
    ACTION_REQUIRED: '🔴 ACTION_REQUIRED',
    ACTION_SOON: '🟡 ACTION_SOON',
    HEALTHY: '🟢 HEALTHY',
    INCONCLUSIVE: '🟣 INCONCLUSIVE',
    UNSUPPORTED_VERSION: '⚫ UNSUPPORTED_VERSION'
  };
  return map[status] || status;
}

function run() {
  const argv = process.argv.slice(2);
  if (argv.includes('--help') || argv.includes('-h')) { printHelp(); process.exit(0); }

  const captureDir = args('capture', 'capture');
  const smFile = args('smartnode', null);
  const outFile = args('out', path.join(captureDir, 'comparison.md'));

  const meta = safeJson(path.join(captureDir, 'capture-metadata.json'));
  const report = safeJson(path.join(captureDir, 'report.json'));
  const snapshot = safeJson(path.join(captureDir, 'snapshot.json'));
  const smText = smFile ? safeRead(smFile) : null;
  const smParsed = extractSmartnode(smText);

  if (!meta || !report) {
    console.error(`ERROR: Could not load capture bundle from '${captureDir}'.`);
    console.error('Run capture.mjs first to populate the bundle.');
    process.exit(1);
  }

  const finding = report.findings?.[0] ?? {};
  const cv = report.contractValues ?? {};
  const bv = report.beaconValues ?? {};

  const lines = [];

  lines.push(`# Cross-Layer Tooling Comparison`);
  lines.push('');
  lines.push(`> Generated by rp-megapool-auditor compare at ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`## Capture Summary`);
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Network | \`${meta.network}\` |`);
  lines.push(`| Megapool Address | \`${meta.megapoolAddress}\` |`);
  lines.push(`| Validator Slot | \`${meta.validatorSlot}\` |`);
  lines.push(`| Beacon Index Queried | \`${meta.beaconIndexQueried}\` |`);
  lines.push(`| Execution Block | \`${meta.executionBlock ?? 'unavailable'}\` |`);
  lines.push(`| Finalized Epoch | \`${meta.finalizedEpoch}\` |`);
  lines.push(`| EL RPC | \`${meta.elRpcUrl}\` |`);
  lines.push(`| CL RPC | \`${meta.clRpcUrl}\` |`);
  lines.push(`| Captured At | \`${meta.capturedAt}\` |`);
  lines.push('');

  lines.push(`## Raw Data Each Tool Sees`);
  lines.push('');
  lines.push(`### Execution-Layer Contract State`);
  lines.push('');
  lines.push('```');
  lines.push(`validatorId:        ${cv.validatorId ?? 'unknown'}`);
  lines.push(`beaconIndex:        ${cv.beaconIndex ?? 'none'}`);
  lines.push(`state:              ${cv.state ?? 'unknown'}`);
  lines.push(`exitNotified:       ${cv.exitNotified}`);
  lines.push(`balanceFinalized:   ${cv.balanceFinalized}`);
  lines.push(`dissolved:          ${cv.dissolved}`);
  lines.push(`dissolutionEpoch:   ${cv.dissolutionEpoch ?? 'none'}`);
  lines.push(`lastDistribution:   ${cv.lastDistributionTime ?? 'none'}`);
  lines.push('```');
  lines.push('');
  lines.push(`### Consensus-Layer Beacon State`);
  lines.push('');
  lines.push('```');
  if (bv) {
    lines.push(`validatorIndex:     ${bv.validatorIndex ?? 'none'}`);
    lines.push(`status:             ${bv.status ?? 'unknown'}`);
    lines.push(`slashed:            ${bv.slashed ?? false}`);
    lines.push(`activationEpoch:    ${bv.activationEpoch ?? 'none'}`);
    lines.push(`exitEpoch:          ${bv.exitEpoch ?? 'none'}`);
    lines.push(`withdrawableEpoch:  ${bv.withdrawableEpoch ?? 'none'}`);
    lines.push(`withdrawalCreds:    ${bv.withdrawalCredentials ?? 'none'}`);
    lines.push(`finalizedEpoch:     ${bv.finalizedEpoch ?? 'none'}`);
    lines.push(`withdrawn:          ${bv.withdrawn ?? false}`);
  } else {
    lines.push('Beacon data: unavailable (INCONCLUSIVE)');
  }
  lines.push('```');
  lines.push('');

  lines.push(`## Side-by-Side Tool Comparison`);
  lines.push('');

  const smState = smParsed?.state ?? '(not captured)';
  const smExit = smParsed?.exitNotified ?? '(not captured)';
  const smBalance = smParsed?.balanceFinalized ?? '(not captured)';
  const smBeacon = smParsed?.beaconIndex ?? '(not captured)';
  const smBeaconStatus = '(not shown — execution layer only)';
  const smWithdrawableEpoch = '(not shown — no beacon join)';
  const smCredential = '(not verified — no beacon join)';
  const smActionSignal = smText
    ? '`rocketpool megapool status` shows `exitNotified: false` but does not indicate if action is overdue'
    : '(not captured)';

  lines.push(`| Information | \`rocketpool megapool status\` | Beacon Explorer | **rp-megapool-auditor** |`);
  lines.push(`|---|---|---|---|`);
  lines.push(`| Contract state | \`${smState}\` | — | \`${cv.state ?? 'unknown'}\` |`);
  lines.push(`| exitNotified | \`${smExit}\` | — | \`${cv.exitNotified}\` |`);
  lines.push(`| balanceFinalized | \`${smBalance}\` | — | \`${cv.balanceFinalized}\` |`);
  lines.push(`| Beacon validator status | ${smBeaconStatus} | \`${bv?.status ?? 'unavailable'}\` | \`${bv?.status ?? 'unavailable'}\` |`);
  lines.push(`| Withdrawable epoch | ${smWithdrawableEpoch} | \`${bv?.withdrawableEpoch ?? 'none'}\` | \`${bv?.withdrawableEpoch ?? 'none'}\` |`);
  lines.push(`| Withdrawal credential check | ${smCredential} | raw hex only | ${finding.ruleId === 'RECON-CRED-001' ? '**MISMATCH DETECTED**' : 'verified match'} |`);
  lines.push(`| Cross-layer action signal | ${smActionSignal} | no contract context | **${statusBadge(finding.status)}** |`);
  lines.push(`| Stable rule ID | none | none | \`${finding.ruleId ?? 'none'}\` |`);
  lines.push(`| Operator action text | none | none | ${finding.operatorAction ? `"${finding.operatorAction.slice(0, 80)}..."` : 'none'} |`);
  lines.push(`| Deadline | none | none | ${finding.deadline ?? 'N/A'} |`);
  lines.push(`| Risk statement | none | none | ${finding.risk ? finding.risk.slice(0, 80) + '...' : 'N/A'} |`);
  lines.push('');

  lines.push(`## Auditor Finding`);
  lines.push('');
  lines.push(`**Rule:** \`${finding.ruleId}\`  `);
  lines.push(`**Status:** ${statusBadge(finding.status)}  `);
  lines.push(`**Severity:** ${finding.severity?.toUpperCase()}  `);
  lines.push('');
  lines.push(`**Explanation:**`);
  lines.push(`> ${finding.explanation}`);
  lines.push('');
  if (finding.operatorAction) {
    lines.push(`**Operator Action Required:**`);
    lines.push(`> ${finding.operatorAction}`);
    lines.push('');
    lines.push(`**Deadline:** ${finding.deadline ?? 'N/A'}  `);
    lines.push(`**Risk:** ${finding.risk ?? 'N/A'}  `);
    lines.push('');
  }
  lines.push(`**Limitation:** *${finding.limitation}*`);
  lines.push('');

  lines.push(`## What This Tool Adds vs. Existing Tools`);
  lines.push('');
  if (smText) {
    lines.push(`- \`rocketpool megapool status\` showed: contract state = \`${smState}\`, exitNotified = \`${smExit}\``);
    lines.push(`- Beacon explorer showed: validator status = \`${bv?.status ?? 'unavailable'}\`, withdrawable epoch = \`${bv?.withdrawableEpoch ?? 'none'}\``);
    lines.push(`- **Neither tool joined these two facts into a single actionable signal.**`);
    lines.push(`- \`rp-megapool-auditor\` joined the execution and beacon states and produced rule \`${finding.ruleId}\`: **${finding.status}**.`);
  } else {
    lines.push(`> Smartnode output was not captured in this bundle.`);
    lines.push(`> To complete this comparison, run:`);
    lines.push(`> \`\`\``);
    lines.push(`> rocketpool megapool status > capture/smartnode-status.txt`);
    lines.push(`> rocketpool megapool validators >> capture/smartnode-status.txt`);
    lines.push(`> \`\`\``);
    lines.push(`> Then re-run compare.mjs with \`--smartnode capture/smartnode-status.txt\`.`);
  }
  lines.push('');

  lines.push(`## Operator Feedback Template`);
  lines.push('');
  lines.push(`Share \`capture/report.md\` and \`capture/smartnode-status.txt\` with a Rocket Pool`);
  lines.push(`node operator or maintainer and ask them to respond to:`);
  lines.push('');
  lines.push('```');
  lines.push('1. Does the cross-layer report show anything that "rocketpool megapool status"');
  lines.push('   or your beacon explorer does not show in one view?');
  lines.push('');
  lines.push('2. Have you or any operator you know missed the notifyValidatorExit deadline');
  lines.push('   because the two states were only visible in separate tools?');
  lines.push('');
  lines.push('3. Would you use this auditor in your monitoring workflow?');
  lines.push('');
  lines.push('4. Is there a state or condition you encounter that this tool does not yet cover?');
  lines.push('```');
  lines.push('');
  lines.push(`---`);
  lines.push(`*Read-only report. No private keys. No transactions. No guarantee of protocol correctness.*`);

  const output = lines.join('\n');
  fs.writeFileSync(outFile, output, 'utf8');
  console.log(`Comparison written to: ${outFile}`);
}

run();
